### ISSUE TITLE
High memory usage for preprocessing

### ISSUE THREAD

**Issue by adamltyson** [SainsburyWellcomeCentre/amap-python#42]
Pre-processing appears to use more memory than necessary, see https://github.com/SainsburyWellcomeCentre/amap-python/issues/39#issuecomment-617262475

No reason why it should be higher than the registration step. There's probably some intermediate steps to delete, or type conversions to be done

**Comment by vigji** [comment]
I guess this happening because of loading of all the stacks in memory (atlas, brainier, filtered), then transformed, and then saved - a more efficient sequence would be file-wise load/transform/save (from what is happening [here](https://github.com/SainsburyWellcomeCentre/amap-python/blob/245dec2e26cfb847fccd35d4467fdf5bb9529eec/amap/config/atlas.py#L43))

**Comment by adamltyson** [comment]
I actually didn't know it was that inefficient. Yes, we should be able to reduce RAM usage in preprocessing by 2/3.

**Comment by vigji** [comment]
Sorry, I thought I pointed you at that already - I was meaning to solve it, happy to do a PR in the next days if you want

**Comment by adamltyson** [comment]
That would be great, thanks!

**Comment by adamltyson** [comment]
Fixed in #48 and #51 max RAM usage for one dataset with the 10um atlas has gone from >64GB to ~20GB.
